- configure system with relative path names

diff --git a/config/confmod.in b/config/confmod.in
--- a/config/confmod.in
+++ b/config/confmod.in
@@ -1,7 +1,29 @@
 dnl Process this file with autoconf to produce a configure script.
+
 AC_INIT(Makefile.in)
 
+parentdir=`pwd`
+relparentdir=.
+configdir="configdir"
+
+while test $parentdir != "/" -a $configdir = "configdir"; do
+	if test -d $parentdir/config ; then
+		configdir=`echo $relparentdir | sed 's/^\.\///'`/config
+	else
+changequote(, )dnl
+		parentdir=`echo $parentdir | sed 's/\/[^\/]*$//'`
+changequote([, ])dnl
+		relparentdir=$relparentdir/..
+	fi
+done
+
+if test $configdir = "configdir" ; then
+	echo "Cannot find configure directory"
+	exit 1
+fi
+
 dnl Configuration Utilities
+AC_CONFIG_AUX_DIR($configdir)
 
 dnl Include general file
 sinclude(general.m4)dnl
@@ -9,10 +31,9 @@ sinclude(general.m4)dnl
 x_makefile=Makefile.x
 AC_SUBST(x_makefile)
 
-thisdir=`pwd`
-cd $srcdir
+AC_SUBST(configdir)
+
 files=`find . -name "*.in" -print | grep -v "/config" | sed -e 's/.in$/ /g'`
-mv $thisdir/confdefs.h $srcdir
 
 AC_OUTPUT($files)
 
