Added configure test for an mkstemp() prototype. Needed on Solaris 2.5.1   where mkstemp() is present in libc but no prototype is defined.

diff --git a/config/configure b/config/configure
--- a/config/configure
+++ b/config/configure
@@ -19003,6 +19003,89 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+echo "$as_me:$LINENO: checking prototype for mkstemp (in libc.h unistd.h stdlib.h)" >&5
+echo $ECHO_N "checking prototype for mkstemp (in libc.h unistd.h stdlib.h)... $ECHO_C" >&6
+
+
+:
+
+ac_includes=""
+for ac_header in libc.h unistd.h stdlib.h
+do
+  ac_safe=`echo "$ac_header" | sed 'y%./+-%__p_%'`
+  if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'}'`\" = yes"; then
+    ac_includes="$ac_includes
+#include<$ac_header>"
+  fi
+done
+if test "${ac_cv_prototype_mkstemp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#ifdef __cplusplus
+extern "C" {
+#endif
+$ac_includes
+#ifdef __cplusplus
+}
+#endif
+typedef union { int member; } dummyStruct;
+#ifdef __cplusplus
+extern "C"
+#endif
+dummyStruct mkstemp(dummyStruct);
+
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "ac_cv_prototype_mkstemp=no"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "ac_cv_prototype_mkstemp=yes"
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+if eval "test \"`echo '$ac_cv_prototype_'mkstemp`\" = yes"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  ac_tr_prototype=HAVE_PROTOTYPE_`echo mkstemp | tr '[a-z]' '[A-Z]'`
+  cat >>confdefs.h <<_ACEOF
+#define $ac_tr_prototype 1
+_ACEOF
+
+  :
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 echo "$as_me:$LINENO: checking prototype for select (in sys/select.h sys/types.h sys/socket.h sys/time.h)" >&5
 echo $ECHO_N "checking prototype for select (in sys/select.h sys/types.h sys/socket.h sys/time.h)... $ECHO_C" >&6
 
@@ -20359,7 +20442,7 @@ if test "${ac_cv_check_std_namespace+set}" = set; then
 else
   ac_link_o='${CXX-g++} -o conftest $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.o $LIBS 1>&5'
 cat > conftest.$ac_ext <<EOF
-#line 20362 "configure"
+#line 20445 "configure"
 #include "confdefs.h"
 
 #include <iostream>
@@ -20720,7 +20803,7 @@ if test "${ac_cv_check_class_template+set}" = set; then
 else
   ac_link_o='${CXX-g++} -o conftest $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.o $LIBS 1>&5'
 cat > conftest.$ac_ext <<EOF
-#line 20723 "configure"
+#line 20806 "configure"
 #include "confdefs.h"
 
 template <class T>
@@ -20793,7 +20876,7 @@ if test "${ac_cv_check_static_template_method+set}" = set; then
 else
   ac_link_o='${CXX-g++} -o conftest $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.o $LIBS 1>&5'
 cat > conftest.$ac_ext <<EOF
-#line 20796 "configure"
+#line 20879 "configure"
 #include "confdefs.h"
 
 void additive(int & i)
@@ -20866,7 +20949,7 @@ if test "${ac_cv_check_function_template+set}" = set; then
 else
   ac_link_o='${CXX-g++} -o conftest $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.o $LIBS 1>&5'
 cat > conftest.$ac_ext <<EOF
-#line 20869 "configure"
+#line 20952 "configure"
 #include "confdefs.h"
 
 template <class T>
