Don't trip over spaces in the absolute path to the code.

diff --git a/config/configure b/config/configure
--- a/config/configure
+++ b/config/configure
@@ -2027,7 +2027,7 @@ common_makefile=Makefile.def
 
 
 ac_aux_dir=
-for ac_dir in `pwd` "$srcdir"/`pwd`; do
+for ac_dir in . "$srcdir"/.; do
   if test -f "$ac_dir/install-sh"; then
     ac_aux_dir=$ac_dir
     ac_install_sh="$ac_aux_dir/install-sh -c"
@@ -2043,8 +2043,8 @@ for ac_dir in `pwd` "$srcdir"/`pwd`; do
   fi
 done
 if test -z "$ac_aux_dir"; then
-  { { echo "$as_me:$LINENO: error: cannot find install-sh or install.sh in \`pwd\` \"$srcdir\"/\`pwd\`" >&5
-echo "$as_me: error: cannot find install-sh or install.sh in \`pwd\` \"$srcdir\"/\`pwd\`" >&2;}
+  { { echo "$as_me:$LINENO: error: cannot find install-sh or install.sh in . \"$srcdir\"/." >&5
+echo "$as_me: error: cannot find install-sh or install.sh in . \"$srcdir\"/." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
